[[heta_app]]
arch = "x86_64"
git-tree-sha1 = "b2265638fb91f32065b17f033b6f9d3ba3b86eab"
libc = "glibc"
os = "linux"

    [[heta_app.download]]
    sha256 = "f1062f0a2322d867dd91f1231f1b1511ff04b8228374fceddd4f211e3fec7d0a"
    url = "https://github.com/hetalang/heta-compiler/releases/download/v0.12.1-beta.0/heta-compiler-linux-x64.tar.gz"
[[heta_app]]
arch = "aarch64"
git-tree-sha1 = "adc25c6b9834d53e324026be9869945eab5d8088"
libc = "glibc"
os = "linux"

    [[heta_app.download]]
    sha256 = "f9c0aac935a7668eb534c3a64668cb3a53cb2db39a04c77efc58e086706c96cd"
    url = "https://github.com/hetalang/heta-compiler/releases/download/v0.12.1-beta.0/heta-compiler-linux-arm64.tar.gz"
[[heta_app]]
arch = "x86_64"
git-tree-sha1 = "2a21807b79169a85388b544975062f6c3cce34ee"
os = "windows"

    [[heta_app.download]]
    sha256 = "091c68a5cc2541981944471267bfb320c2488ce29909bf326dac681397b2f9fe"
    url = "https://github.com/hetalang/heta-compiler/releases/download/v0.12.1-beta.0/heta-compiler-windows-x64.tar.gz"
[[heta_app]]
arch = "x86_64"
git-tree-sha1 = "5ffae064d1a03e6b087fd49a14692ebe4d180702"
os = "macos"

    [[heta_app.download]]
    sha256 = "f5dc26c051adf7c56d6ccee2f3b03d758d961475764bdd9664f3c8cffda2ee6d"
    url = "https://github.com/hetalang/heta-compiler/releases/download/v0.12.1-beta.0/heta-compiler-macos-x64.tar.gz"
[[heta_app]]
arch = "aarch64"
git-tree-sha1 = "c1e12bcc901f33d26525129bb0dc57cacf06c4a1"
os = "macos"

    [[heta_app.download]]
    sha256 = "ac27b13ae83c5fd89703fe5e5d31a282a6b8c4e9d1e8c728f4405fbe1548c033"
    url = "https://github.com/hetalang/heta-compiler/releases/download/v0.12.1-beta.0/heta-compiler-macos-arm64.tar.gz"
