[[heta_app]]
arch = "x86_64"
git-tree-sha1 = "c723259d861717ca3a57fc8855d4c286d4d5e934"
libc = "glibc"
os = "linux"

    [[heta_app.download]]
    sha256 = "e0ac959cf4f98961ed6b45d047bc6441a50479a689187767bb4c6e815442e989"
    url = "https://github.com/hetalang/heta-compiler/releases/download/v0.12.2/heta-compiler-linux-x64.tar.gz"
[[heta_app]]
arch = "aarch64"
git-tree-sha1 = "e4a018b80fe573524b7186689305e0cd3c3cdd71"
libc = "glibc"
os = "linux"

    [[heta_app.download]]
    sha256 = "5c4d1954120c7ddc6ec688ce5c6bfb7bd1b90099aaf30ea664a1b508154723c8"
    url = "https://github.com/hetalang/heta-compiler/releases/download/v0.12.2/heta-compiler-linux-arm64.tar.gz"
[[heta_app]]
arch = "x86_64"
git-tree-sha1 = "cfa9afdf7c0c5426bb307802c592de7555635413"
os = "windows"

    [[heta_app.download]]
    sha256 = "b5d4b41a1da89ab858addb8307a3cf60cd13b9fcbd7055b9daf8194e08cf18ab"
    url = "https://github.com/hetalang/heta-compiler/releases/download/v0.12.2/heta-compiler-windows-x64.tar.gz"
[[heta_app]]
arch = "aarch64"
git-tree-sha1 = "12bee1eada15125cbd13ff89b83917b67061a033"
os = "macos"

    [[heta_app.download]]
    sha256 = "374d52b05cc8a25b9bbdf4cce949ca63b15762466c676598781f49792a05064b"
    url = "https://github.com/hetalang/heta-compiler/releases/download/v0.12.2/heta-compiler-macos-arm64.tar.gz"
