const DYNMS_VERSION = "0.1.0"

const DynMSExpr = Union{Expr,Symbol,Float64}
const DynMSVal = Union{Nothing, Symbol, Float64}

abstract type AbstractDynMSEvent end

struct DynMSState
  initial::DynMSExpr
  equation::DynMSExpr
  is_algebraic::Bool
end

is_algebraic(state::DynMSState) = state.is_algebraic

struct DynMSTimeEvent <: AbstractDynMSEvent
  id::Symbol
  start::DynMSVal
  period::DynMSVal
  stop::DynMSVal
  state_affects::OrderedDict{Symbol,DynMSExpr}
  discrete_affects::OrderedDict{Symbol,DynMSExpr}
  initial_affect::Bool
  is_active::Bool
end

struct DynMSContinuousEvent <: AbstractDynMSEvent
  id::Symbol
  condition::Union{Expr,Symbol}
  state_affects::OrderedDict{Symbol,DynMSExpr}
  discrete_affects::OrderedDict{Symbol,DynMSExpr}
  initial_affect::Bool
  is_active::Bool
end

struct DynMSDiscreteEvent <: AbstractDynMSEvent
  id::Symbol  
  condition::Union{Expr,Symbol}
  state_affects::OrderedDict{Symbol,DynMSExpr}
  discrete_affects::OrderedDict{Symbol,DynMSExpr}
  initial_affect::Bool
  is_active::Bool
end

struct DynMSStopEvent <: AbstractDynMSEvent
  id::Symbol
  condition::Union{Expr,Symbol}
  initial_affect::Bool
  is_active::Bool
end

event_id(event::AbstractDynMSEvent) = event.id
is_active(event::AbstractDynMSEvent) = event.is_active
has_initial_affect(event::AbstractDynMSEvent) = event.initial_affect

# Internal DynMS IR boundary:
# JSON parsing should stop here. Current Platform loading, future ODEProblem
# loading, and future ModelingToolkit system construction should be adapters over
# this parsed DynMSModel/DynMSPlatform plus generated DynMSFunction objects.
struct DynMSModel
  id::Symbol
  constants::OrderedDict{Symbol,Float64} # consider using parameters term in the future
  statics::OrderedDict{Symbol,DynMSExpr} # consider using discrete_parameters (? and dependent_parameters) term in the future
  assignment_rules::OrderedDict{Symbol,DynMSExpr}
  states::OrderedDict{Symbol,DynMSState}
  time_events::OrderedDict{Symbol,DynMSTimeEvent}
  continuous_events::OrderedDict{Symbol,DynMSContinuousEvent}
  discrete_events::OrderedDict{Symbol,DynMSDiscreteEvent}
  stop_events::OrderedDict{Symbol,DynMSStopEvent}
  observables::Vector{Symbol}
end

merge_events(model::DynMSModel) = merge(model.time_events, model.continuous_events, model.discrete_events, model.stop_events)

struct DynMSPlatform
  models::OrderedDict{Symbol,DynMSModel}
  version::String
end

struct DynMSCompileContext
  refs::Dict{String,Symbol}
end

struct DynMSFunction
  name::Symbol
  args::Vector{Symbol}
  body::Expr
end

function parse_dynms_platform(dynms_json::AbstractString)
  return parse_dynms_platform(JSON.parsefile(dynms_json))
end

function parse_dynms_platform(data::AbstractDict)
  dynms_version = string(get(data, "dynms", DYNMS_VERSION))
  dynms_version == DYNMS_VERSION ||
    throw(ArgumentError("Unsupported DynMS format version: $dynms_version. Supported version is: $DYNMS_VERSION"))

  dynms_models = DynMSModel[]
  for model in get(data, "models", Any[])
    isempty_dynms_model(model) && continue
    push!(dynms_models, _parse_dynms_model(model))
  end
 
  isempty(dynms_models) && 
    throw(ArgumentError("No non-empty models found in the provided DynMS JSON."))
  
  heta_compiler_version = string(get(get(data, "generator", Dict{String,Any}()), "version", ""))
  isempty(heta_compiler_version) && 
    throw(ArgumentError("DynMS JSON does not include heta-compiler version. 
    This likely means that the JSON was not generated by heta-compiler version compatible with HetaImporter."))

  return DynMSPlatform(dynms_models, heta_compiler_version)
end

function isempty_dynms_model(model::AbstractDict)
  return all(isempty(get(model, key, Any[])) for key in (
    "constants", "states", "assignments", "derivatives"
  ))
end

function _parse_dynms_model(model::AbstractDict)

  constants = _parse_dynms_constants(model)
  statics = _parse_dynms_statics(model)
  assignment_rules = _parse_dynms_assignments(model)
  states = _parse_dynms_states(model)
  time_events = _parse_dynms_time_events(model)
  continuous_events = _parse_dynms_continuous_events(model)
  discrete_events = _parse_dynms_discrete_events(model)
  stop_events = _parse_dynms_stop_events(model)
  observables = _parse_dynms_observables(model)

  return DynMSModel(
    Symbol(model["id"]),
    constants,
    statics,
    assignment_rules,
    states,
    time_events,
    continuous_events,
    discrete_events,
    stop_events,
    observables
  )
end

#=
function _dynms_expr_to_julia(expr, ctx::DynMSCompileContext)
  payload = _dynms_expr_payload(expr)
  payload isa Number && return payload
  payload isa Bool && return payload

  try
    mathjson_expr = parse(MathJSON.MathJSONFormat, JSON.json(payload))
    return _dynms_mathjson_to_julia(mathjson_expr, ctx)
  catch err
    @warn "MathJSON.jl failed to parse DynMS expression; using fallback parser." expr exception=(err, catch_backtrace())
    return _dynms_raw_expr_to_julia(payload, ctx)
  end
end

function _dynms_expr_payload(expr)
  if expr isa AbstractDict && haskey(expr, "expr")
    format = string(get(expr, "format", "math-json"))
    format == "math-json" ||
      error("Unsupported DynMS expression format '$format'. Only 'math-json' is supported.")
    return expr["expr"]
  end

  return expr
end

function _dynms_mathjson_to_julia(expr::MathJSON.NumberExpr, ctx::DynMSCompileContext)
  return expr.value
end

function _dynms_mathjson_to_julia(expr::MathJSON.SymbolExpr, ctx::DynMSCompileContext)
  return _dynms_symbol_to_julia(expr.name, ctx)
end

function _dynms_mathjson_to_julia(expr::MathJSON.StringExpr, ctx::DynMSCompileContext)
  error("Unsupported DynMS MathJSON string literal: $(expr.value)")
end

function _dynms_mathjson_to_julia(expr::MathJSON.FunctionExpr, ctx::DynMSCompileContext)
  args = Any[_dynms_mathjson_to_julia(arg, ctx) for arg in expr.arguments]
  return _dynms_operator_to_julia(expr.operator, args)
end

function _dynms_raw_expr_to_julia(payload, ctx::DynMSCompileContext)
  if payload isa Number || payload isa Bool
    return payload
  elseif payload isa AbstractString
    return _dynms_symbol_to_julia(payload, ctx)
  elseif payload isa AbstractVector
    isempty(payload) && error("DynMS MathJSON expression cannot be an empty array.")
    operator = Symbol(payload[1])
    args = Any[_dynms_raw_expr_to_julia(arg, ctx) for arg in payload[2:end]]
    return _dynms_operator_to_julia(operator, args)
  elseif payload isa AbstractDict
    haskey(payload, "num") && return _dynms_parse_mathjson_number(payload["num"])
    haskey(payload, "sym") && return _dynms_symbol_to_julia(string(payload["sym"]), ctx)
    haskey(payload, "str") && error("Unsupported DynMS MathJSON string literal: $(payload["str"])")
    haskey(payload, "fn") && return _dynms_raw_expr_to_julia(payload["fn"], ctx)
  end

  error("Unsupported DynMS expression: $payload")
end

function _dynms_parse_mathjson_number(x)
  x isa Number && return x
  s = string(x)
  s == "Infinity" && return Inf
  s == "+Infinity" && return Inf
  s == "-Infinity" && return -Inf
  s == "NaN" && return NaN
  return parse(Float64, s)
end

function _dynms_symbol_to_julia(name::AbstractString, ctx::DynMSCompileContext)
  haskey(ctx.refs, name) && return ctx.refs[name]

  name == "pi" && return :pi
  name == "Pi" && return :pi
  name == "e" && return :(Base.MathConstants.e)
  name == "ExponentialE" && return :(Base.MathConstants.e)
  name == "True" && return true
  name == "False" && return false

  error("Unknown DynMS symbol '$name'.")
end

function _dynms_operator_to_julia(operator::Symbol, args::Vector{Any})
  operator == :Add && return _dynms_call(:+, args; empty=0)
  operator == :Multiply && return _dynms_call(:*, args; empty=1)
  operator == :Negate && return :(-$(only(args)))
  operator == :Subtract && return length(args) == 1 ? :(-$(only(args))) : _dynms_call(:-, args)
  operator == :Divide && return length(args) == 1 ? :(inv($(only(args)))) : _dynms_call(:/, args)
  operator == :Power && return :($(args[1]) ^ $(args[2]))

  operator == :Abs && return :(abs($(only(args))))
  operator == :Sqrt && return :(sqrt($(only(args))))
  operator == :Exp && return :(exp($(only(args))))
  operator == :Ln && return :(log($(only(args))))
  operator == :Log && return length(args) == 1 ? :(log($(only(args)))) : :(log($(args[2]), $(args[1])))
  operator == :Log10 && return :(log10($(only(args))))

  operator == :Sin && return :(sin($(only(args))))
  operator == :Cos && return :(cos($(only(args))))
  operator == :Tan && return :(tan($(only(args))))
  operator == :Arcsin && return :(asin($(only(args))))
  operator == :Arccos && return :(acos($(only(args))))
  operator == :Arctan && return Expr(:call, :atan, args...)

  operator == :Min && return Expr(:call, :min, args...)
  operator == :Max && return Expr(:call, :max, args...)
  operator == :Floor && return :(floor($(only(args))))
  operator == :Ceil && return :(ceil($(only(args))))
  operator == :Round && return :(round($(only(args))))
  operator == :Mod && return :(mod($(args[1]), $(args[2])))

  operator == :Less && return _dynms_pairwise_comparison(Symbol("<"), args)
  operator == :LessEqual && return _dynms_pairwise_comparison(Symbol("<="), args)
  operator == :Greater && return _dynms_pairwise_comparison(Symbol(">"), args)
  operator == :GreaterEqual && return _dynms_pairwise_comparison(Symbol(">="), args)
  operator == :Equal && return _dynms_pairwise_comparison(Symbol("=="), args)
  operator == :NotEqual && return :(!$(_dynms_pairwise_comparison(Symbol("=="), args)))
  operator == :And && return _dynms_short_circuit(Symbol("&&"), args; empty=true)
  operator == :Or && return _dynms_short_circuit(Symbol("||"), args; empty=false)
  operator == :Not && return :(!Bool($(only(args))))
  operator == :Xor && return isempty(args) ? false : Expr(:call, :xor, args...)

  operator == :If && return :($(args[1]) ? $(args[2]) : $(args[3]))

  error("Unsupported DynMS MathJSON operator '$operator'.")
end

function _dynms_call(op::Symbol, args::Vector{Any}; empty=nothing)
  isempty(args) && return empty
  length(args) == 1 && return only(args)
  return Expr(:call, op, args...)
end

function _dynms_pairwise_comparison(op::Symbol, args::Vector{Any})
  length(args) <= 1 && return true
  comparisons = Any[Expr(:call, op, args[i], args[i + 1]) for i in 1:(length(args) - 1)]
  return _dynms_short_circuit(Symbol("&&"), comparisons; empty=true)
end

function _dynms_short_circuit(op::Symbol, args::Vector{Any}; empty)
  isempty(args) && return empty
  ex = args[1]
  for arg in args[2:end]
    ex = Expr(op, ex, arg)
  end
  return ex
end
=#